### ISSUE TITLE
Consider adding 'season' gem to the list

### ISSUE THREAD

**Issue by joaodiogocosta** [planetruby/awesome-activerecord#1]
Hey @geraldb, this is a nice list of resources!

Consider adding [season](https://github.com/joaodiogocosta/season), an ActiveRecord extension to facilitate date/time queries (which are almost always painful to write). It's really useful for apps that rely heavily on queries by date/time such as REST APIs.
Disclaimer: I'm the author :)

**Comment by geraldb** [comment]
Thanks. Great gem. Will get added.
